### ISSUE TITLE
Plugin cannot execute postgresql procedures

### ISSUE THREAD

**Issue by cowwoc** [RagedUnicorn/sql-execute-maven-plugin#6]
https://github.com/RagedUnicorn/sql-execute-maven-plugin/blob/739ad5d77097a64471ca6c3c1a2a998ec45a83d9/src/main/java/com/ragedunicorn/tools/maven/SqlExecuteMojo.java#L306 uses a semicolon as separator.

If you try executing the SQL at https://stackoverflow.com/a/36218838/14731 you will get the following error:

```
Unterminated dollar quote started at position 50 in SQL -- https://stackoverflow.com/a/36218838/14731
[ERROR]
[ERROR] DO
[ERROR] $do$
[ERROR]         DECLARE
[ERROR]         BEGIN
[ERROR]                 CREATE EXTENSION IF NOT EXISTS dblink. Expected terminating $$
```

**Comment by RagedUnicorn** [comment]
Hi @cowwoc 

I see the issue but not really sure how this could be fixed. This plugin is intended for mostly simple test database setups. Tearing them down and recreating them. As you rightly pointed out the logic to determine what is a statement for the plugin is in `SqlExecuteMojo.java` and is a semicolon (`;`). This is in most cases what's expected. I'm not really that familiar with Postgresql especially with more advanced feature such as the example that you linked. I see however that the addon currently build a statement that is not valid on its own. Something like:

```sql
DO $do$ DECLARE _db TEXT := 'some_db';
```

I'm however open for inputs of course. If you can describe a bit more what it is you are trying to achieve I might be able to understand it better. Or if you have a possible solution feel free to post it here.

Cheers,
Michael

**Comment by cowwoc** [comment]
It's fine. I ended up moving this step out of Maven into the machine's deploy script. I'll go ahead and close this issue.
